-- Criações de tabelas

--CPGF
drop table if exists public."tmp_cpgf";
	CREATE TABLE public."tmp_cpgf" (
		"codigo_orgao_superior" integer NULL,
		"nome_orgao_superior" varchar(1024) NULL,
		"codigo_orgao" integer NULL,
		"nome_orgao" varchar(1024) NULL,
		"codigo_unidade_gestora" integer NULL,
		"nome_unidade_gestora" varchar(1024) NULL,
		"ano" integer NULL,
		"mes" integer NULL,
		"cpf_portador" varchar(1024) NULL,
		"nome_portador" varchar(1024) NULL,
		"documento_favorecido" varchar(1024) NULL,
		"nome_favorecido" varchar(1024) NULL,
		"transacao" varchar(1024) NULL,
		"data" varchar(1024) NULL,
		"valor" varchar(1024) NULL
	);
	
	
drop table if exists public."final_cpgf";
	CREATE TABLE public."final_cpgf" (
		"codigo_orgao_superior" integer NULL,
		"nome_orgao_superior" varchar(1024) NULL,
		"codigo_orgao" integer NULL,
		"nome_orgao" varchar(1024) NULL,
		"codigo_unidade_gestora" integer NULL,
		"nome_unidade_gestora" varchar(1024) NULL,
		"ano" integer NULL,
		"mes" integer NULL,
		"cpf_portador" varchar(1024) NULL,
		"nome_portador" varchar(1024) NULL,
		"documento_favorecido" varchar(1024) NULL,
		"nome_favorecido" varchar(1024) NULL,
		"transacao" varchar(1024) NULL,
		"data" date NULL,
		"valor" decimal(20,2) NULL
	)
	
-- CEIS 
drop table if exists public."tmp_ceis";
	CREATE TABLE public."tmp_ceis" (
		"tipo_de_pessoa" varchar(1) null,
		"cpf_ou_cnpj_do_sancionado" varchar(1024) null,
		"nome_informado_pelo_orgao_sancionador" varchar(1024) null,
		"razao_social_cadastro_receita" varchar(1024) null,
		"nome_fantasia_cadastro_receita" varchar(1024) null,
		"numero_do_processo" varchar(1024) null,
		"tipo_sancao" varchar(1024) null,
		"data_inicio_sancao" varchar(10) null,
		"data_final_sancao" varchar(10) null,
		"orgao_sancionador" varchar(1024) null,
		"uf_orgao_sancionador" varchar(2) null,
		"origem_informacoes" varchar(1024) null,
		"data_origem_informacoes" varchar(10) null,
		"data_publicacao" varchar(10) null,
		"publicacao" varchar(1024) null,
		"detalhamento" varchar(2000) null,
		"abragencia_definida_em_decisao_judicial" varchar(1024) null,
		"fundamentacao_legal" varchar(2000) null,
		"descricao_da_fundamentacao_legal" varchar(2500) null,
		"data_do_transito_em_julgado" varchar(10) null,
		"complemento_do_orgao" varchar(2000) null,
		"observacoes" varchar(2500) null
	);

drop table if exists public."final_ceis";
	CREATE TABLE public."final_ceis" (
		"tipo_de_pessoa" varchar(1) null,
		"cpf_ou_cnpj_do_sancionado" varchar(1024) null,
		"nome_informado_pelo_orgao_sancionador" varchar(1024) null,
		"razao_social_cadastro_receita" varchar(1024) null,
		"nome_fantasia_cadastro_receita" varchar(1024) null,
		"numero_do_processo" varchar(1024) null,
		"tipo_sancao" varchar(1024) null,
		"data_inicio_sancao" date  null,
		"data_final_sancao" date null,
		"orgao_sancionador" varchar(1024) null,
		"uf_orgao_sancionador" varchar(2) null,
		"origem_informacoes" varchar(1024) null,
		"data_origem_informacoes" date null,
		"data_publicacao" date null,
		"publicacao" varchar(1024) null,
		"detalhamento" varchar(2000) null,
		"abragencia_definida_em_decisao_judicial" varchar(1024) null,
		"fundamentacao_legal" varchar(2000) null,
		"descricao_da_fundamentacao_legal" varchar(2500) null,
		"data_do_transito_em_julgado" date null,
		"complemento_do_orgao" varchar(2000) null,
		"observacoes" varchar(2500) null
	);

-- PEP
drop table if exists public.tmp_pep;
	create table public.tmp_pep(
	    "cpf" varchar(1024) null,
	    "nome_pep" varchar(1024) null,
	    "sigla_funcao" varchar(1024) null,
	    "descricao_funcao" varchar(1024) null,
	    "nivel_funcao" varchar(1024) null,
	    "nome_orgao" varchar(1024) null,
	    "data_inicio_exercicio" varchar(1024) null,
	    "data_fim_exercicio" varchar(1024) null,
	    "data_fim_carencia" varchar(1024) null    
	);

drop table if exists public.final_pep;
	create table public.final_pep(
	    "cpf" varchar(1024) null,
	    "nome_pep" varchar(1024) null,
	    "sigla_funcao" varchar(1024) null,
	    "descricao_funcao" varchar(1024) null,
	    "nivel_funcao" varchar(1024) null,
	    "nome_orgao" varchar(1024) null,
	    "data_inicio_exercicio" date null,
	    "data_fim_exercicio" date null,
	    "data_fim_carencia" date null
	);


-- Servidores SIAPE -> Cadastro
drop table if exists public."tmp_serv_siape_cad";
CREATE TABLE public."tmp_serv_siape_cad" (
	id_servidor_portal varchar(1024) NULL,
	nome varchar(1024) NULL,
	cpf varchar(1024) NULL,
	matricula varchar(1024) NULL,
	descricao_cargo varchar(1024) NULL,
	classe_cargo varchar(1024) NULL,
	referencia_cargo varchar(1024) NULL,
	padrao_cargo varchar(1024) NULL,
	nivel_cargo varchar(1024) NULL,
	sigla_funcao varchar(1024) NULL,
	nivel_funcao varchar(1024) NULL,
	funcao varchar(1024) NULL,
	codigo_atividade varchar(1024) NULL,
	atividade varchar(1024) NULL,
	opcao_parcial varchar(1024) NULL,
	cod_uorg_lotacao varchar(1024) NULL,
	uorg_lotacao varchar(1024) NULL,
	cod_org_lotacao varchar(1024) NULL,
	org_lotacao varchar(1024) NULL,
	cod_orgsup_lotacao varchar(1024) NULL,
	orgsup_lotacao varchar(1024) NULL,
	cod_uorg_exercicio varchar(1024) NULL,
	uorg_exercicio varchar(1024) NULL,
	cod_org_exercicio varchar(1024) NULL,
	org_exercicio varchar(1024) NULL,
	cod_orgsup_exercicio varchar(1024) NULL,
	orgsup_exercicio varchar(1024) NULL,
	cod_tipo_vinculo varchar(1024) NULL,
	tipo_vinculo varchar(1024) NULL,
	situacao_vinculo varchar(1024) NULL,
	data_inicio_afastamento varchar(1024) NULL,
	data_termino_afastamento varchar(1024) NULL,
	regime_juridico varchar(1024) NULL,
	jornada_de_trabalho varchar(1024) NULL,
	data_ingresso_cargofuncao varchar(1024) NULL,
	data_nomeacao_cargofuncao varchar(1024) NULL,
	data_ingresso_orgao varchar(1024) NULL,
	documento_ingresso_servicopublico varchar(1024) NULL,
	data_diploma_ingresso_servicopublico varchar(1024) NULL,
	diploma_ingresso_cargofuncao varchar(1024) NULL,
	diploma_ingresso_orgao varchar(1024) NULL,
	diploma_ingresso_servicopublico varchar(1024) NULL,
	uf_exercicio varchar(1024) NULL
);

drop table if exists public."final_serv_siape_cad";
CREATE TABLE public.final_serv_siape_cad (
	id_servidor_portal varchar(14) NULL,
	nome varchar(1024) NULL,
	cpf varchar(14) NULL,
	matricula varchar(14) NULL,
	descricao_cargo varchar(1024) NULL,
	classe_cargo varchar(8) NULL,
	referencia_cargo varchar(8) NULL,
	padrao_cargo varchar(8) NULL,
	nivel_cargo varchar(8) NULL,
	sigla_funcao varchar(8) NULL,
	nivel_funcao varchar(8) NULL,
	funcao varchar(1024) NULL,
	codigo_atividade varchar(8) NULL,
	atividade varchar(1024) NULL,
	opcao_parcial varchar(1024) NULL,
	cod_uorg_lotacao varchar(1024) NULL,
	uorg_lotacao varchar(1024) NULL,
	cod_org_lotacao varchar(8) NULL,
	org_lotacao varchar(1024) NULL,
	cod_orgsup_lotacao varchar(8) NULL,
	orgsup_lotacao varchar(1024) NULL,
	cod_uorg_exercicio varchar(1024) NULL,
	uorg_exercicio varchar(1024) NULL,
	cod_org_exercicio varchar(8) NULL,
	org_exercicio varchar(1024) NULL,
	cod_orgsup_exercicio varchar(8) NULL,
	orgsup_exercicio varchar(1024) NULL,
	cod_tipo_vinculo varchar(8) NULL,
	tipo_vinculo varchar(1024) NULL,
	situacao_vinculo varchar(1024) NULL,
	data_inicio_afastamento date NULL,
	data_termino_afastamento date NULL,
	regime_juridico varchar(1024) NULL,
	jornada_de_trabalho varchar(1024) NULL,
	data_ingresso_cargofuncao date NULL,
	data_nomeacao_cargofuncao date NULL,
	data_ingresso_orgao date NULL,
	documento_ingresso_servicopublico varchar(1024) NULL,
	data_diploma_ingresso_servicopublico date NULL,
	diploma_ingresso_cargofuncao varchar(1024) NULL,
	diploma_ingresso_orgao varchar(1024) NULL,
	diploma_ingresso_servicopublico varchar(1024) NULL,
	uf_exercicio varchar(2) NULL
);

-- Servicores SIAPE -> Remuneração
drop table if exists public."tmp_serv_siape_rem";
CREATE TABLE public."tmp_serv_siape_rem" (
	ano varchar(1024) NULL,
	mes varchar(1024) NULL,
	id_servidor_portal varchar(1024) null,
	cpf varchar(1024) null,
	nome varchar(1024) null,
	"rem_bas_bruta_(R$)" varchar(1024) null,
	"rem_bas_bruta_(U$)" varchar(1024) null,
	"abate-teto_(R$)" varchar(1024) null,
	"abate-teto_(U$)" varchar(1024) null,
	"gratif_natal_(R$)" varchar(1024) null,
	"gratif_natal_(U$)" varchar(1024) null,
	"abate-teto_gratif_natal_(R$)" varchar(1024) null,
	"abate-teto_gratif_natal_(U$)" varchar(1024) null,
	"férias_(R$)" varchar(1024) null,
	"férias_(U$)" varchar(1024) null,
	"outras_rem_event_(R$)" varchar(1024) null,
	"outras_rem_event_(U$)" varchar(1024) null,
	"IRRF_(R$)" varchar(1024) null,
	"IRRF_(U$)" varchar(1024) null,
	"PSS_RPGS_(R$)" varchar(1024) null,
	"PSS_RPGS_(U$)" varchar(1024) null,
	"demais_ded_(R$)" varchar(1024) null,
	"demais_ded_(U$)" varchar(1024) null,
	"pensao_militar_(R$)" varchar(1024) null,
	"pensao_militar_(U$)" varchar(1024) null,
	"fundo_saude_(R$)" varchar(1024) null,
	"fundo_saude_(U$)" varchar(1024) null,
	"tx_ocup_imovel_funcional_(R$)" varchar(1024) null,
	"tx_ocup_imovel_funcional_(U$)" varchar(1024) null,
	"rem_pos_deduc_obrig_(R$)" varchar(1024) null,
	"rem_pos_deduc_obrig_(U$)" varchar(1024) null,
	"verbas_indeniz_sist_pes_civil_(R$)(*)" varchar(1024) null,
	"verbas_indeniz_sist_pes_civil_(U$)(*)" varchar(1024) null,
	"verbas_indeniz_sist_pes_militar_(R$)(*)" varchar(1024) null,
	"verbas_indeniz_sist_pes_militar_(U$)(*)" varchar(1024) null,
	"verbas_indeniz_prog_deslig_volunt_mp-792-2017_(R$)" varchar(1024) null,
	"verbas_indeniz_prog_deslig_volunt_mp-792-2017_(U$)" varchar(1024) null,
	"total_verbas_indeniz_(R$)(*)" varchar(1024) null,
	"total_verbas_indeniz_(U$)(*)" varchar(1024) null
);

drop table if exists public."final_serv_siape_rem";
CREATE TABLE public."final_serv_siape_rem" (
	ano int4 NULL,
	mes int4 NULL,
	id_servidor_portal varchar(1024) NULL,
	cpf varchar(1024) NULL,
	nome varchar(1024) NULL,
	"rem_bas_bruta_(R$)" numeric(20,2) NULL,
	"rem_bas_bruta_(U$)" numeric(20,2) NULL,
	"abate-teto_(R$)" numeric(20,2) NULL,
	"abate-teto_(U$)" numeric(20,2) NULL,
	"gratif_natal_(R$)" numeric(20,2) NULL,
	"gratif_natal_(U$)" numeric(20,2) NULL,
	"abate-teto_gratif_natal_(R$)" numeric(20,2) NULL,
	"abate-teto_gratif_natal_(U$)" numeric(20,2) NULL,
	"férias_(R$)" numeric(20,2) NULL,
	"férias_(U$)" numeric(20,2) NULL,
	"outras_rem_event_(R$)" numeric(20,2) NULL,
	"outras_rem_event_(U$)" numeric(20,2) NULL,
	"IRRF_(R$)" numeric(20,2) NULL,
	"IRRF_(U$)" numeric(20,2) NULL,
	"PSS_RPGS_(R$)" numeric(20,2) NULL,
	"PSS_RPGS_(U$)" numeric(20,2) NULL,
	"demais_ded_(R$)" numeric(20,2) NULL,
	"demais_ded_(U$)" numeric(20,2) NULL,
	"pensao_militar_(R$)" numeric(20,2) NULL,
	"pensao_militar_(U$)" numeric(20,2) NULL,
	"fundo_saude_(R$)" numeric(20,2) NULL,
	"fundo_saude_(U$)" numeric(20,2) NULL,
	"tx_ocup_imovel_funcional_(R$)" numeric(20,2) NULL,
	"tx_ocup_imovel_funcional_(U$)" numeric(20,2) NULL,
	"rem_pos_deduc_obrig_(R$)" numeric(20,2) NULL,
	"rem_pos_deduc_obrig_(U$)" numeric(20,2) NULL,
	"verbas_indeniz_sist_pes_civil_(R$)(*)" numeric(20,2) NULL,
	"verbas_indeniz_sist_pes_civil_(U$)(*)" numeric(20,2) NULL,
	"verbas_indeniz_sist_pes_militar_(R$)(*)" numeric(20,2) NULL,
	"verbas_indeniz_sist_pes_militar_(U$)(*)" numeric(20,2) NULL,
	"verbas_indeniz_prog_deslig_volunt_mp-792-2017_(R$)" numeric(20,2) NULL,
	"verbas_indeniz_prog_deslig_volunt_mp-792-2017_(U$)" numeric(20,2) NULL,
	"total_verbas_indeniz_(R$)(*)" numeric(20,2) NULL,
	"total_verbas_indeniz_(U$)(*)" numeric(20,2) NULL
);
